server:
#  服务端口
  port: 8001


spring:
  application:
#    服务名
    name: service-manage
  profiles:
#    环境设置：dev、test、prod
    active: dev
#    数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yanglao?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root
#  返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


#    mybatis日志
mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl